### ISSUE TITLE
poetry run pyright: Installs static node, but does not put it on the path before exec

### ISSUE THREAD

**Issue by blast-hardcheese** [RobertCraigie/pyright-python#157]
Reproduction repo is here: https://github.com/blast-hardcheese/pyright-python-bug

Description
---

Despite installing a dedicated version of node, the system `node` is attempted to be used.

Full traceback is here:

```
/app # PYRIGHT_PYTHON_FORCE_VERSION=latest poetry run pyright
/app/.venv/lib/python3.11/site-packages/nodeenv.py:26: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
 * Install prebuilt node (19.7.0) ..... done.
env: can't execute 'node': No such file or directory

Traceback (most recent call last):
  File "/app/.venv/bin/pyright", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/pyright/cli.py", line 81, in entrypoint
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/pyright/cli.py", line 21, in main
    return run(*args, **kwargs).returncode
           ^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/pyright/cli.py", line 29, in run
    version = node.latest('pyright')
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/pyright/node.py", line 147, in latest
    raise errors.VersionCheckFailed(
pyright.errors.VersionCheckFailed: Version check for pyright failed, see output above.
```

**Comment by RobertCraigie** [comment]
Thanks for the report and sorry for the very long delay.

I'm going to close this as the next release will add support for [`nodejs-wheel`](https://pypi.org/project/nodejs-wheel-binaries/) as an alternative to `nodeenv` which should be more reliable and will be the recommended way to use pyright going forward.

I believe this should also resolve the issue you're seeing.

You can try it out today with
```
python -m pip install 'git+https://github.com/RobertCraigie/pyright-python.git#egg=pyright[nodejs]'
```
When released, it will be
```
pip install pyright[nodejs]
```
Please let me know if you run into any issues with this new setup.
