### ISSUE TITLE
An internal error occurred while type checking file: Error: Debug Failure. False expression.

### ISSUE THREAD

**Issue by lexicalunit** [RobertCraigie/pyright-python#180]
If I downgrade to pyright version 1.1.308 I do not get this error. It's only after upgrading to version 1.1.309 that this error occurs. I'm running this on an Apple M1 Max laptop.

```shell
$ poetry run pyright --version
pyright 1.1.309

$ poetry run python --version
Python 3.10.10

$ macosver
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261

$ poetry --version
Poetry (version 1.4.2)

$ rm -rf ~/.cache/pyright-python

$ poetry run pyright .

added 1 package, and audited 2 packages in 798ms

found 0 vulnerabilities
An internal error occurred while type checking file "/Users/me/source/lexicalunit/spellbot/src/spellbot/client.py": Error: Debug Failure. False expression.
    at a.lock (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeVarContext.ts:372:9)
    at validateFunctionArgumentTypes (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10449:28)
    at validateFunctionArgumentTypesWithContext (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10222:20)
    at validateFunctionArguments (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10702:16)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8666:48)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
    at doForEachSubtype (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
    at expandSubtype (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
    at s.validateCallArguments [as timeOperation] (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
    at validateNewMethod (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:317:19)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:113:35)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19126:28)
    at s.useSpeculativeMode [as timeOperation] (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
    at validateConstructorArguments (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:108:15)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8966:55)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
    at doForEachSubtype (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
    at expandSubtype (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
    at validateCallArguments (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
    at getTypeOfCall (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7563:36)
    at getTypeOfExpression (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:958:30)
    at evaluateTypesForAssignmentStatement (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:14513:39)
    at evaluateTypesForStatement (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18254:25)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19866:17)
    at evaluateTypeForSubnode (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18368:9)
    at getInferredTypeOfDeclaration (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19865:32)
    at forEach (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20182:36)
    at Array.forEach (<anonymous>)
    at getEffectiveTypeOfSymbolForUsage (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20126:15)
    at getTypeOfName (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:4157:43)
    at getTypeOfExpression (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:943:30)
    at validateArgType (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10996:40)
    at forEach (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10419:43)
    at Array.forEach (<anonymous>)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10400:44)
    at useSpeculativeMode (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19126:28)
    at validateFunctionArgumentTypes (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10399:17)
    at validateFunctionArgumentTypesWithContext (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10222:20)
    at validateFunctionArguments (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10702:16)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8666:48)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
    at doForEachSubtype (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
    at expandSubtype (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
    at validateCallArguments (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
    at getTypeOfCall (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7563:36)
    at getTypeOfExpression (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:958:30)
    at forEach (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:17141:66)
    at Array.forEach (<anonymous>)
    at inferFunctionReturnType (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:17138:59)
    at disableSpeculativeMode (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20459:48)
    at getFunctionInferredReturnType (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20458:25)
    at getFunctionEffectiveReturnType (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20407:20)
    at partiallySpecializeFunctionForBoundClassOrObject (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:24782:9)
    at bindFunctionToClassOrObject (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:24603:24)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:5698:55)
    at suppressDiagnostics (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19099:28)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:5681:48)
    at mapSubtypes (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:335:32)
    at applyDescriptorAccessMethod (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:5541:16)
    at _t (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:5439:38)
Error performing analysis: Error: Debug Failure. False expression.
    at a.lock (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeVarContext.ts:372:9)
    at validateFunctionArgumentTypes (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10449:28)
    at validateFunctionArgumentTypesWithContext (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10222:20)
    at validateFunctionArguments (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10702:16)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8666:48)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
    at doForEachSubtype (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
    at expandSubtype (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
    at s.validateCallArguments [as timeOperation] (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
    at validateNewMethod (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:317:19)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:113:35)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19126:28)
    at s.useSpeculativeMode [as timeOperation] (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/common/timing.ts:40:20)
    at validateConstructorArguments (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/constructors.ts:108:15)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8966:55)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
    at doForEachSubtype (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
    at expandSubtype (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
    at validateCallArguments (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
    at getTypeOfCall (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7563:36)
    at getTypeOfExpression (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:958:30)
    at evaluateTypesForAssignmentStatement (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:14513:39)
    at evaluateTypesForStatement (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18254:25)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19866:17)
    at evaluateTypeForSubnode (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:18368:9)
    at getInferredTypeOfDeclaration (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19865:32)
    at forEach (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20182:36)
    at Array.forEach (<anonymous>)
    at getEffectiveTypeOfSymbolForUsage (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20126:15)
    at getTypeOfName (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:4157:43)
    at getTypeOfExpression (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:943:30)
    at validateArgType (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10996:40)
    at forEach (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10419:43)
    at Array.forEach (<anonymous>)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10400:44)
    at useSpeculativeMode (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19126:28)
    at validateFunctionArgumentTypes (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10399:17)
    at validateFunctionArgumentTypesWithContext (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10222:20)
    at validateFunctionArguments (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:10702:16)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8666:48)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3653:39)
    at doForEachSubtype (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:487:9)
    at expandSubtype (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3646:13)
    at mapSubtypesExpandTypeVars (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:3677:13)
    at validateCallArguments (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:8595:26)
    at getTypeOfCall (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:7563:36)
    at getTypeOfExpression (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:958:30)
    at forEach (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:17141:66)
    at Array.forEach (<anonymous>)
    at inferFunctionReturnType (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:17138:59)
    at disableSpeculativeMode (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20459:48)
    at getFunctionInferredReturnType (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20458:25)
    at getFunctionEffectiveReturnType (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:20407:20)
    at partiallySpecializeFunctionForBoundClassOrObject (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:24782:9)
    at bindFunctionToClassOrObject (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:24603:24)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:5698:55)
    at suppressDiagnostics (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:19099:28)
    at callback (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:5681:48)
    at mapSubtypes (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeUtils.ts:335:32)
    at applyDescriptorAccessMethod (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:5541:16)
    at _t (/Users/me/.cache/pyright-python/1.1.309/node_modules/pyright/dist/pyright-internal/src/analyzer/typeEvaluator.ts:5439:38)
```

Source code is here: https://github.com/lexicalunit/spellbot/blob/main/src/spellbot/client.py

**Comment by lexicalunit** [comment]
I see the same issue on Ubuntu 22.042 LTS, in github actions CI/CD. You can view the entire pipeline and errors here: https://github.com/lexicalunit/spellbot/actions/runs/5016378390/jobs/8993169395?pr=1162

It starts:
```log
E       AssertionError: pyright issues:
E         
E         added 1 package, and audited 2 packages in 2s
E         
E         found 0 vulnerabilities
E         
E         An internal error occurred while type checking file "/home/runner/work/spellbot/spellbot/tests/services/test_awards.py": Error: Debug Failure. False expression.
```

**Comment by RobertCraigie** [comment]
Hey @lexicalunit, thanks for the bug report. This looks like a bug with the type checker itself which has been reported on the main Pyright repository & will be fixed in the next release - https://github.com/microsoft/pyright/issues/5129.
