### ISSUE TITLE
pyright 1.1.387 won't start with node v20.18.0: Invalid regular expression SyntaxError 

### ISSUE THREAD

**Issue by hholst80** [RobertCraigie/pyright-python#320]
**Describe the bug**

pyright does not run.

```
# python3 --version
Python 3.12.2
# node --version
v20.18.0 
```

**Code or Screenshots**

```
# source venv/bin/activate.fish
(venv) root@xps ... (master)
# pip freeze
nodeenv==1.9.1
pyright==1.1.387
typing_extensions==4.12.2
(venv) root@xps ... (master)
# pyright

[snip]

SyntaxError: Invalid regular expression: /\(\?P?<([\p{ID_Start}$_][\p{ID_Continue}$_\u200C\u200D]*)>/u: Invalid property name in character class
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at o.f.require (/root/.cache/pyright-python/1.1.387/node_modules/pyright/dist/pyright.js:1:2316)
    at /root/.cache/pyright-python/1.1.387/node_modules/pyright/dist/pyright.js:1:1784
    at Array.reduce (<anonymous>)

Node.js v20.18.0
(venv) root@xps ... (master) [0|1]
# 
```

**Comment by RobertCraigie** [comment]
Sorry for the delayed response, are you still running into this?

**Comment by hholst80** [comment]
```
                                                           

SyntaxError: Invalid regular expression: /\(\?P?<([\p{ID_Start}$_][\p{ID_Continue}$_\u200C\u200D]*)>/u: Invalid property name in character class
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at o.f.require (/root/.cache/pyright-python/1.1.387/node_modules/pyright/dist/pyright.js:1:2316)
    at /root/.cache/pyright-python/1.1.387/node_modules/pyright/dist/pyright.js:1:1784
    at Array.reduce (<anonymous>)

Node.js v20.18.0
(venv) root@xps ~/qwer [0|1]
# cat requirements.txt
nodeenv==1.9.1
pyright==1.1.387
typing_extensions==4.12.2
(venv) root@xps ~/qwer
# 
```

**Comment by hholst80** [comment]
Seems to be resolved with the latest version of pyright:

```
(venv) root@xps ~/qwer
# pip install pyright --upgrade
Requirement already satisfied: pyright in ./venv/lib/python3.12/site-packages (1.1.387)
Collecting pyright
  Downloading pyright-1.1.400-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: nodeenv>=1.6.0 in ./venv/lib/python3.12/site-packages (from pyright) (1.9.1)
Requirement already satisfied: typing-extensions>=4.1 in ./venv/lib/python3.12/site-packages (from pyright) (4.12.2)
Downloading pyright-1.1.400-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 10.8 MB/s eta 0:00:00
Installing collected packages: pyright
  Attempting uninstall: pyright
    Found existing installation: pyright 1.1.387
    Uninstalling pyright-1.1.387:
      Successfully uninstalled pyright-1.1.387
Successfully installed pyright-1.1.400
(venv) root@xps ~/qwer
# pyright
0 errors, 0 warnings, 0 informations 
(venv) root@xps ~/qwer
# 
````

**Comment by RobertCraigie** [comment]
Thanks, closing this as resolved then.

**Comment by hholst80** [comment]
I ran into this problem again.  I can just pin to 1.1.400 until I can find time to upgrade to a later version of node than the v20 that I am on.  I do not think this is an issue with your python wrapper but since we are here, someone might find this and find this information useful.

`chk.sh`

```
for pver in $(seq 387 403)
do
        semver=1.1.$pver
        pip install --upgrade pyright==$semver >& /dev/null
        if pyright --help >& /dev/null
        then
                printf "$semver\tOK\n"
        else
                printf "$semver\tERROR\n"
        fi
done
```

Output from `bash chk.sh`

```
1.1.387 ERROR
1.1.388 ERROR
1.1.389 OK
1.1.390 OK
1.1.391 OK
1.1.392 OK
1.1.393 OK
1.1.394 OK
1.1.395 OK
1.1.396 OK
1.1.397 OK
1.1.398 OK
1.1.399 OK
1.1.400 OK
1.1.401 ERROR
1.1.402 ERROR
1.1.403 ERROR
```

```
SyntaxError: Invalid regular expression: /[\p{L}\p{N}\p{Pc}\p{Mn}\p{Mc}]+$/u: Invalid property name in character class
    at wrapSafe (node:internal/modules/cjs/loader:1378:20)
    at Module._compile (node:internal/modules/cjs/loader:1428:41)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at o.f.require (/root/omnicoder/invoice/postprocess/.venv/lib/python3.12/site-packages/pyright/dist/dist/pyright.js:1:2294)
    at /root/omnicoder/invoice/postprocess/.venv/lib/python3.12/site-packages/pyright/dist/dist/pyright.js:1:1762
    at Array.reduce (<anonymous>)

Node.js v20.18.0
```
