### ISSUE TITLE
"return non-zero exit status 2" failure coming from nodeenv. Windows temp-file dependent issue

### ISSUE THREAD

**Issue by uglycoyote** [RobertCraigie/pyright-python#45]
On some Windows 10 machines, I'm running in to this failure when trying to start up pyright:

```
D:\Project\NLG>c:\python36\python -m pyright
 * Environment already exists: C:\Users\admin\AppData\Local\Temp\pyright-python.admin\env
Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python36\lib\site-packages\pyright\__main__.py", line 5, in <module>
    entrypoint()
  File "c:\python36\lib\site-packages\pyright\cli.py", line 46, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "c:\python36\lib\site-packages\pyright\cli.py", line 20, in main
    return run(*args, **kwargs).returncode
  File "c:\python36\lib\site-packages\pyright\cli.py", line 30, in run
    npx = node.version('npx')
  File "c:\python36\lib\site-packages\pyright\node.py", line 116, in version
    proc = run(target, '--version', stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "c:\python36\lib\site-packages\pyright\node.py", line 86, in run
    binary = _ensure_available(target)
  File "c:\python36\lib\site-packages\pyright\node.py", line 34, in _ensure_available
    return Binary(path=_ensure_node_env(target), strategy=Strategy.NODEENV)
  File "c:\python36\lib\site-packages\pyright\node.py", line 52, in _ensure_node_env
    _install_node_env()
  File "c:\python36\lib\site-packages\pyright\node.py", line 79, in _install_node_env
    subprocess.run(args, check=True)
  File "c:\python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['c:\\python36\\python.exe', '-m', 'nodeenv', 'C:\\Users\\admin\\AppData\\Local\\Temp\\pyright-python.admin\\env']' returned non-zero exit status 2.

```

If I delete the temp folder that's listed, then running `python -m pyright` will pause while installing node but then immediately fail in a way that's similar to the above (during a `_ensure_available` call after the installation). Whereas whenever running `python -m pyright` after that it will fail immediately. 

If running `python -m nodeenv` directly, I get the same message "Environment already exists" with a process return code 2.

So, return code 2 doesn't seem like an error to me -- that's good if the environment already exists, right?  

Is the bug then that python-pyright is interpreting this error code 2 as a fatal error whereas it should be interpreting it as a success?

On a different Windows 10 machine, python-pyright appears to be working but the behaviour is quite different.  Each time I run, it reinstalls node in a new temp folder.   The temp file paths are things like `C:\Users\admin\AppData\Local\Temp\pyright-18412-XGp1w1LhcUJv`, and I have a build up of quite a number of those temp folders with different random alpanumeric endings. (they seem empty, so at least it's not a major memory leak of leaving a full node installation in each of those).  

Should python-pyright be reinstalling node each time it is run, or trying to reuse existing temp instlallations?  If it should be trying to reuse, then the behaviour on the "working" machine also seems like a bug.

I'm not sure what is different about my different Windows machines where they seem to use a different temp-folder strategy like this.

**Comment by uglycoyote** [comment]
Update... I tried to hack my way around the issues by changing the implementation of `_install_node_env` to be consider the error code 2 to be acceptable by removing the `check=True` from subprocess.run (`check=True` means it throws an exception for any nonzero return code) and instead explicitly throwing an exception if it returns anything other than zero or two:

```
def _install_node_env() -> None:
    log.debug('Installing nodeenv to %s', ENV_DIR)
    args = [sys.executable, '-m', 'nodeenv', str(ENV_DIR)]
    log.debug('Running command with args: %s', args)
    result = subprocess.run(args)
    if  ( result.returncode != 0 and result.returncode != 2 ):
        raise Exception(f"nodeenv installation failure with error code {result.returncode}")
```

Having done that I just run in to a subsequent problem:

```
pyright.errors.BinaryNotFound: Expected npx binary to exist at C:\Users\admin\AppData\Local\Temp\pyright-python.admin\env\bin\npx but was not found
```

Whereas the actual location of `npx` is a `C:\Users\admin\AppData\Local\Temp\pyright-python.admin\env\Scripts`. 

This seems like a common pythonesque paradigm -- putting things in a `Scripts` folder on windows which would be in a `bin` directory on other platforms.  The pyright-python sourcecode has "bin" hardcoded: 

```
ENV_DIR: Path = get_env_dir()
BINARIES_DIR: Path = ENV_DIR / 'bin'
```

So I presume that either pyright-python was not designed to run on Windows and/or does not have a significant enough Windows user base to surface these issues?

**Comment by RobertCraigie** [comment]
The original error you're encountering is because of the hardcoded `bin` path which then surfaces the error you subsequently encountered.

> So I presume that either pyright-python was not designed to run on Windows and/or does not have a significant enough Windows user base to surface these issues?

I've had other bug reports from people using windows which were fixed so it should work on windows.

This seems to be a quirk to do with `nodeenv`, looking through the `nodeenv` code it does save the node binaries to the `Scripts` directory on windows, this case should be handled as well.

**Comment by uglycoyote** [comment]
I tried a few more levels of hacking to see if I could get things to work:

* I replaced the hard coded bin reference with `BINARIES_DIR: Path = ENV_DIR / 'Scripts'
`
* The machine that I was testing on actually had `bash` in the path (from cygwin I think), even though it was a windows machine, so it was trying to use that because it was there, but of course bash would fail to recognize the windows temp file folder sync it uses /`cygdrive ` paths.   So that part seemed like an issue

* I tried replacing the `bash -c` with `cmd /c`but this failed because the command is a double-command with "active && realcommand" which is a bash paradigm that windows' cmd.exe doesn't recognize, so thats another non-windowsy thing that would have to be fixed to make the code cross-platform

After getting that far in to hacking it I decided I was probably better off just to use `nodeenv` directly and avoid using pyright-python and go the slightly-more-manual approach of using `nodeenv` directly (which seems to work fine on Windows).  I'm able to get pyright to work with just four commands that way.   

`pip install nodeenv`
`python -m nodeenv nodeenv`
`\nodeenv\Scripts\activate`
`npx --yes pyright`

I think it would be a good idea to either address the cross-platform windows issue on this repo though or just put a disclaimer on the Readme that it doesn't work on Windows.  Since Microsoft's repo specifically points to yours as the recommended way to run pyright on the command line (https://github.com/Microsoft/pyright#command-line) it didn't even cross my mind that this would not work on Windows, but now that I've spent a few hours looking at it, it seems there are quite a few fixes needed before it would work on Windows.

**Comment by RobertCraigie** [comment]
I see, thanks for investigating!

I was under the impression that pyright-python should work on Windows because of #10. Although looking through it now, it seems that the tests are flawed.

I'll look into fixing those issues you've mentioned as soon as possible.

**Comment by uglycoyote** [comment]
Thank you!   I actually have other reasons to use `nodeenv` directly so I don't mind the approach that I have settled on there, so there's not urgent need for the fixes to `pyright-python` on my end, but I appreciate that this project exists to  try to make the installation and usage of pyright dead-simple for users who aren't accustomed to nodejs, so thanks for maintaining it and I'm sure some future Windows users will appreciate the fixes.   And I don't mind testing it if you don't have a Windows machine and are in need of a tester.

**Comment by halveez** [comment]
Just ran into this same issue and wanted to ask if there was any update.

**Comment by RobertCraigie** [comment]
@halveez Unfortunately no update at the moment, I've been very busy recently.

**Comment by uglycoyote** [comment]
@halveez I have been continuing to use the python `nodeenv` package for this as mentioned above, which works fine on Windows.    (nodeenv is what pyright-python is using under the hood, but I'm using it directly, instead)

```
pip install nodeenv
python -m nodeenv nodeenv
\nodeenv\Scripts\activate
npx --yes pyright
```

Which I find to be a simple and good alternative for python-centric use of pyright on Windows machines where NodeJS hasn't been installed.

**Comment by blakeNaccarato** [comment]
## Workaround for running pyright in a dependency-aware fashion

The advice by @uglycoyote above works, with some caveats. Not that you actually have to run `.\nodeenv\scripts\Activate.ps1` instead of `\nodeenv\Scripts\activate` in his version.

But let's say you have a virtual environment for your project at `.venv` in the root of the project, with project dependencies (say `pandas`) in there, as well as `pyright` installed via `pip install pyright`. If you had run `npx -y pyright` out of a separate `nodeenv` folder like the above solution, it won't "know" about your `pandas` dependency over in `.venv`, and will complain whenever it sees `pandas` in your code.

But it turns out you can instruct `nodeenv` to fix up your current `.venv` as follows, which allows `pyright` obtained from `PyPi` to run in a dependency-aware way without the "return non-zero exit status 2" error. This is how you do that:

```Shell
. '.venv/Scripts/activate'
pip install nodeenv
nodeenv -p
```

If your `.venv` already has `pyright` installed via `pip install pyright` or similar, then running `pyright` at the terminal should work now. Running `nodeenv -p` modified our `.venv/Scripts/activate` script, exposing `npm` and such to the command line. But we are actually just taking advantage of a side-effect that now `pyright` should work without any additional `npm install` or `npx` commands.

## More details

Of course you could omit `pip install pyright`, and instead source it via `npm install -g pyright` now, which will source Pyright directly from NPM. But maybe you have a `requirements.txt` somewhere with `pyright==X.X.XXX` pinned to a version in it (like I do), and you'd like to avoid lugging around a `package.json` just for a single NPM dependency in your pure Python project. Either way, by manually handling `nodeenv` ourselves, we sidestep this issue and have `pyright` run in a dependency-aware fashion.

Remember you have to run `. '.venv/Scripts/activate` whenever you start your terminal. It's usually a good idea to do this in your terminal profile, like `~\Documents\PowerShell\Microsoft.PowerShell_profile.ps1` for PowerShell on Windows, the equivalent of a `.bashrc`.

## The "Let's just install NodeJS" route

You could also just install [NodeJS](https://nodejs.org/en/) on your Windows machine, side-stepping `nodeenv` and `pip install pyright` altogether. You would source `pyright` directly from your system global NodeJS via `npm install -g pyright`. If you want to install a specific version of pyright on a per-project basis, you would have to keep a `package.json` in your repo that looks like this:

```json
{
  "private": true,
  "devDependencies": {
    "pyright": "X.X.XXX"
  }
}
```
You would then run something like `npm install` or `npm install --no-save` (to avoid writing the lockfile). You would have to make sure the `node_modules` or `node_modules/.bin` directory was added to your system path to get access to `pyright` on command line. If you do your order of operations correctly (activating `.venv` as well), you can run `pyright` in a dependency-aware manner like this.

## A ground-up example of the first workaround

Here's a more verbose example where I set up the environment and give comments along the way as to the specifics of this example. Your approach will likely vary depending on your tooling:

```Shell
# Install the virtual environment
# For example, install using the default `py` launcher for Windows, optionally specifying the Python version
py -3.10 -m venv .venv

# Activate the virtual environment, exposing isolated scripts like `pip`, `python`, etc.
. '.venv/Scripts/activate'

# It's usually a good idea to upgrade pip and install the basics like this.
# You might also install your package manager here, like `flit` or `poetry`.
python -m pip install -U pip   # Need to do it via `python -m ...` on Windows for reasons
pip install -U setuptools wheel  # Can just use `pip` directly going forward

# Install the local package in editable mode, along with its dependencies.
# This will differ depending on your package manager of choice.
pip install -e .

# Let's say these are a mix of your package requirements and development requirements.
# In practice these would probably be specified in requirements files, `setup.py`, or `pyproject.toml`.
# Note that we are installing the Python wrapper for pyright here.
pip install pandas nodeenv pyright

# We need to manually run `nodeenv` here to avoid the "return non-zero exit status 2" issue
# The `-p` flag causes node to install to your current `.venv`, modifying '.venv/Scripts/activate' accordingly.
nodeenv -p

# Let's try pyright and see if it works!
pyright
```

**Comment by RobertCraigie** [comment]
@uglycoyote @halveez @blakeNaccarato this issue should now be fixed in `v1.1.280`!

I managed to reproduce the original "non-zero exit status 2" issue coming from `nodeenv` and now have a complete testing setup that handles this case to ensure there are no regressions.

Also thanks @blakeNaccarato for the detailed investigation of workarounds!

> Each time I run, it reinstalls node in a new temp folder

@uglycoyote I have not investigated this issue but I haven't noticed it myself, are you still running into it?

**Comment by RobertCraigie** [comment]
Thanks for the details @uglycoyote! Those `pip install` errors are very strange, I've never encountered them before...

> The first run took about 2 minutes to "install the prebuilt node

That's not ideal, would you say you have a reasonably fast internet connection? I suspect the bottleneck here may just be how slow the Windows FS is but there may be things we can do to optimise this.
