### ISSUE TITLE
Node version check is dodgy

### ISSUE THREAD

**Issue by matthewdeanmartin** [RobertCraigie/pyright-python#5]
Node dumps all sorts of garbage when you run npx.CMD --version, you can't assume it is a version number alone.
```
 cmd.exe "/c pyright"
2021-08-06 13:16:24,473 - DEBUG - pyright.node - Checking for global target binary: npm
2021-08-06 13:16:24,490 - DEBUG - pyright.node - Found global binary at: C:\Program Files\nodejs\npm.CMD
2021-08-06 13:16:24,490 - DEBUG - pyright.node - Global binary exists at: C:\Program Files\nodejs\npm.CMD
2021-08-06 13:16:24,490 - DEBUG - pyright.node - Running node command with args: ['C:\\Program Files\\nodejs\\npm.CMD', 'info', 'pyright', 'version']
2021-08-06 13:16:26,547 - DEBUG - pyright.node - Version check for pyright returning (node:21540) ExperimentalWarning: The fs.promises API is experimental
2021-08-06 13:16:26,547 - DEBUG - pyright.node - Checking for global target binary: npx
2021-08-06 13:16:26,560 - DEBUG - pyright.node - Found global binary at: C:\Program Files\nodejs\npx.CMD
2021-08-06 13:16:26,561 - DEBUG - pyright.node - Global binary exists at: C:\Program Files\nodejs\npx.CMD
2021-08-06 13:16:26,561 - DEBUG - pyright.node - Running node command with args: ['C:\\Program Files\\nodejs\\npx.CMD', '--version']
Traceback (most recent call last):
  File "C:\Users\matth\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\matth\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\matth\.virtualenvs\search_service-3Tw2H1cF\Scripts\pyright.exe\__main__.py", line 7, in <module>
  File "c:\users\matth\.virtualenvs\search_service-3tw2h1cf\lib\site-packages\pyright\cli.py", line 37, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "c:\users\matth\.virtualenvs\search_service-3tw2h1cf\lib\site-packages\pyright\cli.py", line 19, in main
    return run(*args, **kwargs).returncode
  File "c:\users\matth\.virtualenvs\search_service-3tw2h1cf\lib\site-packages\pyright\cli.py", line 29, in run
    npx = node.version('npx')
  File "c:\users\matth\.virtualenvs\search_service-3tw2h1cf\lib\site-packages\pyright\node.py", line 121, in version
    info = tuple(int(value) for value in output.splitlines()[0].split('.'))
  File "c:\users\matth\.virtualenvs\search_service-3tw2h1cf\lib\site-packages\pyright\node.py", line 121, in <genexpr>
    info = tuple(int(value) for value in output.splitlines()[0].split('.'))
ValueError: invalid literal for int() with base 10: '(node:10820) ExperimentalWarning: The fs'

matth@DESKTOP-FANFFGU MINGW64 ~/public_record/search_service (CPRS-2036-build-script)
$ npx --version
(node:3388) ExperimentalWarning: The fs.promises API is experimental
7.13.0
```

**Comment by RobertCraigie** [comment]
@matthewdeanmartin Thanks for the bug report, I've just pushed a fix for this, can you please try it out and confirm whether or not this fixes your issue.

**Comment by RobertCraigie** [comment]
Closing this now, if this issue still persists please let me know.
