### ISSUE TITLE
Pyright raising errors.VersionCheckFailed even though it exists

### ISSUE THREAD

**Issue by olatelnyx** [RobertCraigie/pyright-python#81]
Similar to the issue below. 
_Originally posted by @RobertCraigie in https://github.com/RobertCraigie/pyright-python/issues/56#issuecomment-1152588253_

see logs 
```
root@691b3d39624c:/app# env PYRIGHT_PYTHON_IGNORE_NPX_CHECK=1 pyright -p pyrightconfig-ci.json 
2022-06-13 12:06:58,393 - DEBUG - pyright.node - Checking for global target binary: npm
2022-06-13 12:06:58,404 - DEBUG - pyright.node - Found global binary at: /usr/bin/npm
2022-06-13 12:06:58,405 - DEBUG - pyright.node - Global binary exists at: /usr/bin/npm
2022-06-13 12:06:58,407 - DEBUG - pyright.node - Running node command with args: ['/usr/bin/npm', 'info', 'pyright', 'version']
2022-06-13 12:07:04,976 - DEBUG - pyright.node - Version check for pyright returning 1.1.254
2022-06-13 12:07:04,980 - DEBUG - pyright.node - Checking for global target binary: npx
2022-06-13 12:07:04,986 - DEBUG - pyright.node - Found global binary at: /usr/bin/npx
2022-06-13 12:07:04,988 - DEBUG - pyright.node - Global binary exists at: /usr/bin/npx
2022-06-13 12:07:04,992 - DEBUG - pyright.node - Running node command with args: ['/usr/bin/npx', '--version']
2022-06-13 12:07:07,736 - DEBUG - pyright.node - Version check for npx returning (8, 11, 0)
2022-06-13 12:07:07,738 - DEBUG - pyright.node - Checking for global target binary: npx
2022-06-13 12:07:07,739 - DEBUG - pyright.node - Found global binary at: /usr/bin/npx
2022-06-13 12:07:07,739 - DEBUG - pyright.node - Global binary exists at: /usr/bin/npx
2022-06-13 12:07:07,740 - DEBUG - pyright.node - Running node command with args: ['/usr/bin/npx', '--silent', '--yes', '--', 'pyright@1.1.254', '-p', 'pyrightconfig-ci.json']
2022-06-13 12:07:14,440 - DEBUG - pyright.node - Checking for global target binary: npm
2022-06-13 12:07:14,445 - DEBUG - pyright.node - Found global binary at: /usr/bin/npm
2022-06-13 12:07:14,446 - DEBUG - pyright.node - Global binary exists at: /usr/bin/npm
2022-06-13 12:07:14,449 - DEBUG - pyright.node - Running node command with args: ['/usr/bin/npm', 'info', 'pyright', 'version']

Traceback (most recent call last):
  File "/usr/local/bin/pyright", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/site-packages/pyright/cli.py", line 81, in entrypoint
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/python3.10/site-packages/pyright/cli.py", line 21, in main
    return run(*args, **kwargs).returncode
  File "/usr/local/lib/python3.10/site-packages/pyright/cli.py", line 29, in run
    version = node.latest('pyright')
  File "/usr/local/lib/python3.10/site-packages/pyright/node.py", line 145, in latest
    raise errors.VersionCheckFailed(
pyright.errors.VersionCheckFailed: Version check for pyright failed, see output above.
root@691b3d39624c:/app# 
root@691b3d39624c:/app# /usr/bin/npm info pyright version
1.1.254
root@691b3d39624c:/app# 
```

**Comment by olatelnyx** [comment]
An issue with the docker image. Switching to newer docker image fixes the issue

**Comment by RobertCraigie** [comment]
That is certainly a weird issue, glad you managed to find a fix and thank you for documenting it!
